INSERT INTO sentence_frags VALUES (4, '<noun> is <adverb> making a mistake');
INSERT INTO sentence_frags VALUES (5, 'I <verb> <noun>');
INSERT INTO sentence_frags VALUES (6, '<noun> just <verb> my day');
INSERT INTO sentence_frags VALUES (7, '<noun> is such a <adverb> place');
INSERT INTO sentence_frags VALUES (8, '<noun> is such a <adverb> person');
INSERT INTO sentence_frags VALUES (9, 'I think <adverb> disregarding <noun> is bad');
INSERT INTO sentence_frags VALUES (10, '<noun> is <adjective>');
INSERT INTO sentence_frags VALUES (11, '<noun> is doing <adverb>');
INSERT INTO sentence_frags VALUES (12, 'How can <noun> be so <adjective>');
INSERT INTO sentence_frags VALUES (13, 'How can <noun> <verb> that');
INSERT INTO sentence_frags VALUES (14, 'What a <adjective> decision from <noun>');
INSERT INTO sentence_frags VALUES (15, 'We should really <verb> <noun> more');
INSERT INTO sentence_frags VALUES (16, 'We need to <verb> <noun>');
INSERT INTO sentence_frags VALUES (17, '<noun> <adverb> a decision there');
INSERT INTO sentence_frags VALUES (18, '<noun> just said the <adjective> thing');
INSERT INTO sentence_frags VALUES (19, 'I think <noun> is being so <adjective> right now');
INSERT INTO sentence_frags VALUES (20, 'What <adjective> stuff is going on in <noun> right now');
INSERT INTO sentence_frags VALUES (21, 'I feel <adjective> for <noun>');
INSERT INTO sentence_frags VALUES (22, 'Who thinks <noun> is doing a <adjective> job');
INSERT INTO sentence_frags VALUES (23, '<noun> is <adverb> <adjective>');
INSERT INTO sentence_frags VALUES (24, 'I think <noun> is <adverb> <verb> us');
INSERT INTO sentence_frags VALUES (25, '<verb> <noun>');
INSERT INTO sentence_frags VALUES (26, '<noun> is acting <adverb>');
INSERT INTO sentence_frags VALUES (27, 'One day <noun> will <verb>');
INSERT INTO sentence_frags VALUES (28, 'I really <verb> <noun>! It really makes <adjective> to think about it');
INSERT INTO sentence_frags VALUES (29, 'Somebody better <verb> <noun> or things could get ugly');
