# Generated by Django 3.0.3 on 2020-02-21 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=200, verbose_name='Group name')),
                ('topic_name', models.CharField(max_length=200, verbose_name='Topic name')),
                ('num_users', models.IntegerField()),
                ('percent_female', models.IntegerField()),
                ('twitter_or_facebook', models.CharField(choices=[('twitter', 'Twitter'), ('facebook', 'Facebook')], default='twitter', max_length=100, verbose_name='Type of posts')),
                ('num_posts', models.IntegerField()),
                ('sentiment', models.CharField(choices=[('pos', 'positive'), ('neg', 'negative')], max_length=100, verbose_name='Sentiment')),
                ('topic_noun', models.CharField(max_length=100, verbose_name='Noun relating to topic')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('json_output', models.CharField(max_length=100, verbose_name='Name for json file output')),
            ],
        ),
    ]
