# Generated by Django 3.0.3 on 2020-04-06 14:55

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('description', models.TextField()),
                ('num_users', models.PositiveIntegerField(default=0)),
                ('percent_female', models.PositiveIntegerField(default=50, validators=[django.core.validators.MaxValueValidator(100)])),
                ('logo', models.FilePathField(path='/img')),
            ],
        ),
        migrations.CreateModel(
            name='HashTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_time', models.DateTimeField()),
                ('tag', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InputModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=200, verbose_name='Group name')),
                ('topic_name', models.CharField(max_length=200, verbose_name='Topic name')),
                ('num_users', models.PositiveIntegerField(default=0)),
                ('percent_female', models.PositiveIntegerField(default=50, validators=[django.core.validators.MaxValueValidator(100)])),
                ('twitter_or_facebook', models.CharField(choices=[('twitter', 'Twitter'), ('facebook', 'Facebook')], default='twitter', max_length=100, verbose_name='Type of posts')),
                ('num_posts', models.PositiveIntegerField(default=0)),
                ('sentiment', models.CharField(choices=[('pos', 'positive'), ('neg', 'negative')], max_length=100, verbose_name='Sentiment')),
                ('topic_noun', models.CharField(max_length=100, verbose_name='Noun relating to topic')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('json_output', models.CharField(max_length=100, verbose_name='Name for json file output')),
            ],
        ),
        migrations.CreateModel(
            name='TwitterUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_name', models.CharField(max_length=250)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('gender', models.CharField(max_length=250)),
                ('age', models.IntegerField()),
                ('followers', models.IntegerField()),
                ('favourites', models.IntegerField()),
                ('statuses', models.IntegerField()),
                ('description', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 4, 6, 14, 55, 42, 627364))),
                ('country', models.CharField(max_length=250)),
                ('province', models.CharField(max_length=250)),
                ('language', models.CharField(max_length=250)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spasms.Exercise')),
            ],
        ),
        migrations.CreateModel(
            name='TweetRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=250, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('num_posts', models.PositiveIntegerField(default=0)),
                ('sentiment', models.CharField(choices=[('pos', 'positive'), ('neg', 'negative')], default='pos', max_length=100, verbose_name='Sentiment')),
                ('topic_noun', models.CharField(default='none', max_length=100, verbose_name='Noun relating to topic')),
                ('start_date', models.DateField(default=datetime.datetime(2020, 4, 6, 14, 55, 42, 626198))),
                ('end_date', models.DateField(default=datetime.datetime(2020, 4, 6, 14, 55, 42, 626236))),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spasms.Exercise', to_field='name')),
            ],
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=280)),
                ('creation_time', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spasms.TwitterUser')),
                ('hashtags', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spasms.HashTag')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spasms.TweetRun')),
            ],
        ),
        migrations.AddField(
            model_name='hashtag',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='spasms.TwitterUser'),
        ),
        migrations.AddField(
            model_name='hashtag',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spasms.Exercise'),
        ),
    ]
