# Generated by Django 3.0.3 on 2020-02-21 18:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spasms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputmodel',
            name='num_posts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inputmodel',
            name='num_users',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inputmodel',
            name='percent_female',
            field=models.PositiveIntegerField(default=50, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
