# Generated by Django 3.0.3 on 2020-04-06 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spasms', '0002_auto_20200406_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetrun',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 6, 14, 55, 51, 332545)),
        ),
        migrations.AlterField(
            model_name='tweetrun',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 6, 14, 55, 51, 332513)),
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 6, 14, 55, 51, 333571)),
        ),
    ]
