# Generated by Django 3.0.3 on 2020-03-19 20:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spasms', '0002_auto_20200319_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='hashtags',
            field=models.ForeignKey(null=True,on_delete=django.db.models.deletion.CASCADE, to='spasms.HashTag'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tweetrun',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 19, 20, 0, 48, 158023)),
        ),
        migrations.AlterField(
            model_name='tweetrun',
            name='label',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='tweetrun',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 19, 20, 0, 48, 157993)),
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 19, 20, 0, 48, 159104)),
        ),
    ]
