# Generated by Django 3.0.3 on 2020-03-02 16:35

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spasms', '0004_auto_20200226_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='num_users',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exercise',
            name='percent_female',
            field=models.PositiveIntegerField(default=50, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='tweetrun',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 2, 16, 35, 31, 978248)),
        ),
        migrations.AddField(
            model_name='tweetrun',
            name='num_posts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tweetrun',
            name='sentiment',
            field=models.CharField(choices=[('pos', 'positive'), ('neg', 'negative')], default='pos', max_length=100, verbose_name='Sentiment'),
        ),
        migrations.AddField(
            model_name='tweetrun',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2020, 3, 2, 16, 35, 31, 978220)),
        ),
        migrations.AddField(
            model_name='tweetrun',
            name='topic_noun',
            field=models.CharField(default='none', max_length=100, verbose_name='Noun relating to topic'),
        ),
    ]
