# Generated by Django 3.0.3 on 2020-04-06 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spasms', '0002_auto_20200319_1903'),
        ('spasms', '0004_auto_20200319_2001'),
    ]

    operations = [
    ]
