# Generated by Django 3.0.3 on 2020-04-15 15:16

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spasms', '0005_merge_20200406_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('description', models.TextField()),
                ('num_users', models.PositiveIntegerField(default=0)),
                ('percent_female', models.PositiveIntegerField(default=50, validators=[django.core.validators.MaxValueValidator(100)])),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spasms.Exercise', to_field='name')),
            ],
        ),
        migrations.DeleteModel(
            name='InputModel',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='num_users',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='percent_female',
        ),
        migrations.RemoveField(
            model_name='hashtag',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='tweetrun',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='twitteruser',
            name='exercise',
        ),
        migrations.AlterField(
            model_name='tweetrun',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 15, 15, 15, 33, 419752)),
        ),
        migrations.AlterField(
            model_name='tweetrun',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 15, 15, 15, 33, 419728)),
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 15, 15, 15, 33, 420595)),
        ),
        migrations.AddField(
            model_name='hashtag',
            name='group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='spasms.Group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tweetrun',
            name='group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='spasms.Group', to_field='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='twitteruser',
            name='group',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='spasms.Group'),
            preserve_default=False,
        ),
    ]
