# Generated by Django 3.0.3 on 2020-04-17 16:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spasms', '0007_auto_20200415_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spasms.Exercise'),
        ),
        migrations.AlterField(
            model_name='tweetrun',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 17, 16, 38, 8, 42642)),
        ),
        migrations.AlterField(
            model_name='tweetrun',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 17, 16, 38, 8, 42613)),
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 17, 16, 38, 8, 44037)),
        ),
    ]
