# Generated by Django 3.0.3 on 2020-04-17 16:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spasms', '0008_auto_20200417_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweetrun',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 17, 16, 42, 16, 15106)),
        ),
        migrations.AlterField(
            model_name='tweetrun',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spasms.Group'),
        ),
        migrations.AlterField(
            model_name='tweetrun',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2020, 4, 17, 16, 42, 16, 15043)),
        ),
        migrations.AlterField(
            model_name='twitteruser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 17, 16, 42, 16, 17037)),
        ),
    ]
