# Generated by Django 3.0.3 on 2020-03-10 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spasms', '0009_auto_20200310_1742'),
        ('spasms', '0007_auto_20200310_1707'),
    ]

    operations = [
    ]
