# Generated by Django 3.0.3 on 2020-03-19 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spasms', '0008_auto_20200310_1852'),
        ('spasms', '0010_merge_20200310_1811'),
    ]

    operations = [
    ]
